### ISSUE TITLE
Add Description of Project to README.md

### ISSUE THREAD

**Issue by htjjen** [MrHayato/VacBanChecker#11]
Hi,
I would like to add some description of your project in the README.md. If it's possible, please let me know what you'd like me to add.  Thank you!

------
Background:
As a beginner contributor, I'm working on an assignment for my technical writing course, which requires students to make real-world revisions and have them accepted.

I will make PR(s) after my revisions. Please feel free to correct me if I missed anything. Thank you!

**Comment by WillsonHaw** [comment]
Yes, please go ahead.
