### ISSUE TITLE
Revise "How to Use" section in README

### ISSUE THREAD

**Issue by htjjen** [MrHayato/VacBanChecker#12]
I would like to make some revisions to the `How to Use` section. 

----
Background:
As a beginner contributor, I'm working on an assignment for my technical writing course, which requires students to make real-world revisions and have them accepted.

I will make PR(s) after my revisions. Please feel free to correct me if I missed anything. Thank you!

**Comment by WillsonHaw** [comment]
Yes, please go ahead.
