### ISSUE TITLE
No longer works as of 5/8/2015

### ISSUE THREAD

**Issue by bionicsheep** [MrHayato/VacBanChecker#2]
output from console: 

GET https://api.steampowered.com/ISteamUser/GetPlayerBans/v1/?key=F6F90A461E30D…66,76561198107901057,76561198087954233,76561198165784343,76561198216327864 403 (Forbidden)

**Comment by ElevatorSteve** [comment]
yep, does not work atm

**Comment by WillsonHaw** [comment]
DIdn't even see this issue show up in my email... my notifications must be off or something... This should be fixed as of 6 days ago. The API key was wrong so I generated a new one. If you get latest it should be fixed.

**Comment by WillsonHaw** [comment]
The change was made in this commit: https://github.com/MrHayato/VacBanChecker/commit/5b72e980b3d0dc7670016ecfe0a52b138da9f4b3
